apiVersion: v1
kind: ConfigMap
metadata:
  name: lightspeed-hub-proxy-ca
  namespace: openshift-lightspeed
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/name: lightspeed-hub
