#!/usr/bin/env bash
# Build three controller images and record their immutable deployment digests.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/common.sh
source "$DIR/../../scripts/common.sh"

usage() {
  printf '%s\n' \
    'Usage: install.sh [--lock-current]' \
    '' \
    'Build, push, and lock the three controller images.' \
    '--lock-current skips build and push, resolving published latest tags.'
}

lock_current=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --lock-current) lock_current=true ;;
    -h|--help) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
  shift
done

load_demo_config
require_command git
require_command skopeo

SOURCE_CACHE="${DEMO_ROOT}/.demo/sources"
IMAGE_REGISTRY="${IMAGE_REGISTRY:-quay.io/kgordeev}"
PULL_SECRET="${PULL_SECRET:-${HOME}/.config/openshift/pull-secret}"
if [[ "$lock_current" == false ]]; then
  require_command make
  require_file "$PULL_SECRET"
fi

AGENTIC_OPERATOR_SOURCE_URL="${AGENTIC_OPERATOR_SOURCE_URL:-https://github.com/openshift/lightspeed-agentic-operator.git}"
AGENTIC_OPERATOR_SOURCE_REF="${AGENTIC_OPERATOR_SOURCE_REF:-main}"
HUB_SOURCE_URL="${HUB_SOURCE_URL:-https://github.com/openshift/lightspeed-hub.git}"
HUB_SOURCE_REF="${HUB_SOURCE_REF:-main}"
AAA_SOURCE_URL="${AAA_SOURCE_URL:-https://github.com/openshift/lightspeed-agentic-alerts-adapter.git}"
AAA_SOURCE_REF="${AAA_SOURCE_REF:-main}"

AGENTIC_OPERATOR_BUILD_IMAGE="${IMAGE_REGISTRY}/lightspeed-agentic-operator:latest"
HUB_BUILD_IMAGE="${IMAGE_REGISTRY}/lightspeed-hub-operator:latest"
AAA_BUILD_IMAGE="${IMAGE_REGISTRY}/lightspeed-agentic-alerts-adapter:latest"

require_latest_tag() {
  [[ "$1" == *:latest ]] || fail "image must use the latest build tag: $1"
}

sync_source() {
  local name="$1"
  local source_url="$2"
  local source_ref="$3"
  local source_dir="${SOURCE_CACHE}/${name}"

  if [[ ! -d "${source_dir}/.git" ]]; then
    git clone --no-checkout "$source_url" "$source_dir"
  fi

  git -C "$source_dir" remote set-url origin "$source_url"
  git -C "$source_dir" fetch --prune origin "$source_ref"
  git -C "$source_dir" checkout --detach FETCH_HEAD
  git -C "$source_dir" rev-parse HEAD
}

resolve_digest() {
  local image="$1"
  local digest

  digest="$(skopeo inspect --format '{{.Digest}}' "docker://${image}")"
  printf '%s@%s\n' "${image%:*}" "$digest"
}

write_lock() {
  local agentic_commit="$1"
  local hub_commit="$2"
  local aaa_commit="$3"
  local lock_dir
  local lock_tmp

  lock_dir="$(dirname "$IMAGE_LOCK_FILE")"
  mkdir -p "$lock_dir"
  lock_tmp="$(mktemp "${lock_dir}/image-lock.env.XXXXXX")"
  trap 'rm -f "$lock_tmp"' RETURN

  {
    printf '# Generated by manifests/00-images/install.sh. Do not edit.\n'
    printf 'AGENTIC_OPERATOR_IMAGE="%s"\n' "$(resolve_digest "$AGENTIC_OPERATOR_BUILD_IMAGE")"
    printf 'HUB_IMAGE="%s"\n' "$(resolve_digest "$HUB_BUILD_IMAGE")"
    printf 'AAA_IMAGE="%s"\n' "$(resolve_digest "$AAA_BUILD_IMAGE")"
    printf 'LOCK_AGENTIC_OPERATOR_SOURCE_URL="%s"\n' "$AGENTIC_OPERATOR_SOURCE_URL"
    printf 'LOCK_AGENTIC_OPERATOR_SOURCE_COMMIT="%s"\n' "$agentic_commit"
    printf 'LOCK_HUB_SOURCE_URL="%s"\n' "$HUB_SOURCE_URL"
    printf 'LOCK_HUB_SOURCE_COMMIT="%s"\n' "$hub_commit"
    printf 'LOCK_AAA_SOURCE_URL="%s"\n' "$AAA_SOURCE_URL"
    printf 'LOCK_AAA_SOURCE_COMMIT="%s"\n' "$aaa_commit"
  } > "$lock_tmp"

  mv "$lock_tmp" "$IMAGE_LOCK_FILE"
  trap - RETURN
}

require_latest_tag "$AGENTIC_OPERATOR_BUILD_IMAGE"
require_latest_tag "$HUB_BUILD_IMAGE"
require_latest_tag "$AAA_BUILD_IMAGE"

mkdir -p "$SOURCE_CACHE"
agentic_commit="$(sync_source agentic-operator "$AGENTIC_OPERATOR_SOURCE_URL" "$AGENTIC_OPERATOR_SOURCE_REF")"
hub_commit="$(sync_source hub "$HUB_SOURCE_URL" "$HUB_SOURCE_REF")"
aaa_commit="$(sync_source alerts-adapter "$AAA_SOURCE_URL" "$AAA_SOURCE_REF")"

if [[ "$lock_current" == true ]]; then
  write_lock "$agentic_commit" "$hub_commit" "$aaa_commit"
  printf 'wrote immutable image lock from published latest tags: %s\n' \
    "$IMAGE_LOCK_FILE"
  exit 0
fi

REGISTRY_AUTH_FILE="$PULL_SECRET" make -C "${SOURCE_CACHE}/agentic-operator" \
  docker-build IMG="$AGENTIC_OPERATOR_BUILD_IMAGE"
make -C "${SOURCE_CACHE}/agentic-operator" docker-push \
  IMG="$AGENTIC_OPERATOR_BUILD_IMAGE"
REGISTRY_AUTH_FILE="$PULL_SECRET" make -C "${SOURCE_CACHE}/hub" \
  docker-build IMG="$HUB_BUILD_IMAGE"
make -C "${SOURCE_CACHE}/hub" docker-push IMG="$HUB_BUILD_IMAGE"
REGISTRY_AUTH_FILE="$PULL_SECRET" make -C "${SOURCE_CACHE}/alerts-adapter" \
  container-push IMAGE_NAME="${AAA_BUILD_IMAGE%:*}" IMAGE_TAG=latest

write_lock "$agentic_commit" "$hub_commit" "$aaa_commit"
printf 'wrote immutable image lock: %s\n' "$IMAGE_LOCK_FILE"
